### ISSUE TITLE
升级到.NET 5,6 

### ISSUE THREAD

**Issue by geffzhang** [DebugST/STNodeEditor#3]
.NET 5,6 已经支持Winform了，可以升级了

**Comment by DebugST** [comment]
哈哈 你可以看到 目前这个版本使用 .Net3.5在vs2010下编译的 偷偷告诉你 其实在这之前 我一直用.net2.0后来觉得确实太老了了 才换成3.5的 不过工程都有 你需要5的话可以直接升级 虽然我还没用过高版本的语法 起码我觉得3.5的语法应该还是兼容的吧

**Comment by geffzhang** [comment]
https://www.codeproject.com/Articles/24385/Have-a-Great-DesignTime-Experience-with-a-Powerful

**Comment by HaojieTian** [comment]
支持WPF吗？

**Comment by FreeVB** [comment]
请问这个是做什么用的？演示好像也没有正式的表现实际功能。

**Comment by DebugST** [comment]
> 请问这个是做什么用的？演示好像也没有正式的表现实际功能。

可以参考`blender`或者`蓝图`，至于实际功能需要开使用者需求。节点编辑器只是提供流程化的一个过程。

**Comment by oz01** [comment]
求maui版( •̀ ω •́ )y，凡是用户可以操作的类建议都给个list<object> 方便储存数据，否则需要额外自己搞个字典，非常麻烦
