### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by GlodenBoy** [DebugST/STNodeEditor#5]
一开始看到这个东西的时候 就觉得老哥很牛b，也在脑海里一直想这个东西的用处。
也在想项目里是否什么东西可以用上，后来想这确实不就是一个蓝图的功能么，目前在调研使用的时候发现几个问题：

1. 视图里的右键功能没有，实际上可以把左侧的功能加入到右键，而不是每次都需要拖进去。
比如，a 组件 右键 显示out可以连线的组件。

2. 缺少整合蓝图的功能，意思就是如果后期数量多了，顶部也没有小缩略图，也看不到整体的样子的，线看起来乱七八糟的，无法一键让他按固定的样子排列好。

3. 因为用到的是类似流程的蓝图，我本来是想利用这个蓝图功能生成对应的代码文件，也就是每个node 为一段代码，目前还没想到如何实现

最后还是感谢老哥开源出这么牛b的东西。

**Comment by DebugST** [comment]
1. 关于这个点 之前确实有考虑过 类似Blender中Shift+A 直接就是鼠标位置中弹出可以创建的节点 后来想了想这个功能留给开发者自己实现吧 因为如果由控件是实现了 代码耦合度就太高了 不一定每个开发者都需要这个样子 不过下一个版本中可以考虑在STNodeEditorPanel中去集成 因为STNodeEditorPanel的设定就是一个组合功能
2. 这个问题设计之初我也考虑到过 不过做着做着渐渐的就忘了，不过如果下个版本更新的话 将会提供缩略图 至于线乱七八糟和节点位置的排列 这个我还没有想好
3. 这个我就不太清楚你的具体需求了 如果一个节点表示一段代码 最终想要组合这些节点的代码的话 那么你是可以通过遍历得到连线关系的

**Comment by GlodenBoy** [comment]
> 1. 关于这个点 之前确实有考虑过 类似Blender中Shift+A 直接就是鼠标位置中弹出可以创建的节点 后来想了想这个功能留给开发者自己实现吧 因为如果由控件是实现了 代码耦合度就太高了 不一定每个开发者都需要这个样子 不过下一个版本中可以考虑在STNodeEditorPanel中去集成 因为STNodeEditorPanel的设定就是一个组合功能
> 2. 这个问题设计之初我也考虑到过 不过做着做着渐渐的就忘了，不过如果下个版本更新的话 将会提供缩略图 至于线乱七八糟和节点位置的排列 这个我还没有想好
> 3. 这个我就不太清楚你的具体需求了 如果一个节点表示一段代码 最终想要组合这些节点的代码的话 那么你是可以通过遍历得到连线关系的
> 
> 非常感谢你的反馈与支持

我可能没说明白，我想做一个 类似 连线就能进行“简单编程”的东西，每个节点是我自己定义的代码片段功能，按连线的顺序跑。

**Comment by DebugST** [comment]
> 
> 
> > 1. 关于这个点 之前确实有考虑过 类似Blender中Shift+A 直接就是鼠标位置中弹出可以创建的节点 后来想了想这个功能留给开发者自己实现吧 因为如果由控件是实现了 代码耦合度就太高了 不一定每个开发者都需要这个样子 不过下一个版本中可以考虑在STNodeEditorPanel中去集成 因为STNodeEditorPanel的设定就是一个组合功能
> > 2. 这个问题设计之初我也考虑到过 不过做着做着渐渐的就忘了，不过如果下个版本更新的话 将会提供缩略图 至于线乱七八糟和节点位置的排列 这个我还没有想好
> > 3. 这个我就不太清楚你的具体需求了 如果一个节点表示一段代码 最终想要组合这些节点的代码的话 那么你是可以通过遍历得到连线关系的
> > 
> > 非常感谢你的反馈与支持
> 
> 我可能没说明白，我想做一个 类似 连线就能进行“简单编程”的东西，每个节点是我自己定义的代码片段功能，按连线的顺序跑。
> 目前项目还没有用到，所以细节部分没有看源码，相信未来应该能用上。

那你说的可能是这里我提到的需求？
[https://blog.csdn.net/crystal_lz/article/details/117131080](https://blog.csdn.net/crystal_lz/article/details/117131080)
下面 “关于下个版本” 中所提到的。

**Comment by GlodenBoy** [comment]
> > > 1. 关于这个点 之前确实有考虑过 类似Blender中Shift+A 直接就是鼠标位置中弹出可以创建的节点 后来想了想这个功能留给开发者自己实现吧 因为如果由控件是实现了 代码耦合度就太高了 不一定每个开发者都需要这个样子 不过下一个版本中可以考虑在STNodeEditorPanel中去集成 因为STNodeEditorPanel的设定就是一个组合功能
> > > 2. 这个问题设计之初我也考虑到过 不过做着做着渐渐的就忘了，不过如果下个版本更新的话 将会提供缩略图 至于线乱七八糟和节点位置的排列 这个我还没有想好
> > > 3. 这个我就不太清楚你的具体需求了 如果一个节点表示一段代码 最终想要组合这些节点的代码的话 那么你是可以通过遍历得到连线关系的
> > > 
> > > 非常感谢你的反馈与支持
> > 
> > 
> > 我可能没说明白，我想做一个 类似 连线就能进行“简单编程”的东西，每个节点是我自己定义的代码片段功能，按连线的顺序跑。
> > 目前项目还没有用到，所以细节部分没有看源码，相信未来应该能用上。
> 
> 那你说的可能是这里我提到的需求？
> https://blog.csdn.net/crystal_lz/article/details/117131080
> 下面 “关于下个版本” 中所提到的。

是的，只不过有点区别的是 节点之间的交互比较少，基本就是执行逻辑。
