### ISSUE TITLE
ReadOnlyModel 建议可以添加做为STNode属性

### ISSUE THREAD

**Issue by GlodenBoy** [DebugST/STNodeEditor#6]
ReadOnlyModel 建议可以作为 STNode 属性，开启后只针对该节点， 外部的改成readOnly 作为全局统一的。

现在我想针对局部的节点是没有办法的，只能改造了

**Comment by DebugST** [comment]
> ReadOnlyModel 建议可以作为 STNode 属性，开启后只针对该节点， 外部的改成readOnly 作为全局统一的。
> 
> 现在我想针对局部的节点是没有办法的，只能改造了

感谢你的一直使用。。最近也收集了一些之前用户提供的建议。。在开始构思3.0版本的一些东西
关于你的这个问题目前可以通过Editor的SelectedChanged来根据当前选择的节点来判断是否 readonly 。或者通过给STNode添加ReadOlny属性 并提供Changed这样的事件 然后属性编辑器的ReadOnly采用STNode的值

关于你这个问题我也想了一下。。如果把ReadOnly移动到STNode中的话 需要批量的时候 比如当前需要锁定所有节点的时候 需要循环每个节点去设置之，，也会变得繁琐。。到时候我思考一下是否需要改变处理方式
