### ISSUE TITLE
STNode 定义只读属性保存后，再读取时会报异常

### ISSUE THREAD

**Issue by AzThinker** [DebugST/STNodeEditor#7]
假如定义如下属性
[STNodeProperty("Name", "唯一标识")]
public string Name { get { return this.Guid.ToString(); } }
则在保存后，再打开会出现异常。
我定义了如下特性
public class STNoSaveAttribute: Attribute
{
}
并修改 STNode的OnSaveNode事件中
foreach (var p in t.GetProperties()) {
var attrs = p.GetCustomAttributes(true);
// 增加检测
if (attrs.Where(s => s is STNoSaveAttribute).Count() > 0) continue;
……
}

这样就没有错误了
只是一种方案，也许有更好的。

**Comment by AzThinker** [comment]
这样也可以的。
如果想序列化到数据库，或者成json格式的数据时，并不是所有的属性值都需要序列化。所以，增加几个标记特性，也是一种不错的选择。

**Comment by DebugST** [comment]
是的，新的特性会增加。
```cs
enum SaveModel{
All,
OnlyMarked,
ExcludeMarked
}
[STNode(...,SaveModel.MarkedOnly)]
public class XXXNode : STNode{
    public int Test_1{get;set}
    [STNodeProperty("key","description"),STNodePropertyMark]
    public int Test_2{get;set}
}
```
名称暂定。
